name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        lua-version: [5.1, 5.2, 5.3, 5.4, luajit-2.1.0-beta3]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: ${{ matrix.lua-version }}
        
    - name: Setup Luarocks  
      uses: leafo/gh-actions-luarocks@v4
      
    - name: Install dependencies
      run: |
        luarocks install busted
        luarocks install luacov
        luarocks install luacheck
        
    - name: Run tests
      run: |
        busted --verbose tests/
        
    - name: Run linter
      run: |
        luacheck lua/ tests/ --globals vim
        
    - name: Generate coverage
      run: |
        busted --verbose --coverage tests/
        luacov
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.lua-version == '5.1'
      with:
        file: ./luacov.report.out
        flags: unittests
        name: codecov-umbrella